# Grab variables from the specific variable group
variables:
- group: 'nutter-demo'

trigger:
  batch: true
  branches:
    include:
    - '*'

  tags:
    include:
      - v*.*
      - prod

stages:
- stage: onPush
  condition: |
    and(
      ne(variables['Build.SourceBranch'], 'refs/heads/releases'),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    )
  jobs:
  - job: onPushJob
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.7'
      inputs:
        versionSpec: 3.7

    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - script: |
        python -m pip install --upgrade pip nutter
      displayName: 'Install dependencies'

# https://docs.databricks.com/projects.html#projects-api-experimental
    - script: |
        echo "Checking out the $(Build.SourceBranchName) branch"
        curl -s -n -X POST -o "/tmp/$(Build.SourceBranchName)-out.json" "$DATABRICKS_HOST/api/2.0/projects/fetch-and-checkout" \
          -H "Authorization: Bearer $DATABRICKS_TOKEN" \
          -d "{\"path\": \"/Projects/christopher.chalcraft@databricks.com/Staging\", \"branch\": \"$(Build.SourceBranchName)\"}"; \
          cat "/tmp/$(Build.SourceBranchName)-out.json"; \
          grep -v error_code "/tmp/$(Build.SourceBranchName)-out.json"
      env:
        DATABRICKS_HOST: $(DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
      displayName: 'Update Staging project'

    - script: |
        nutter run '/Projects/christopher.chalcraft@databricks.com/Staging/' --cluster_id $(CLUSTER_ID) --recursive --junit_report
      env:
        DATABRICKS_HOST: $(DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
      displayName: 'Execute Nutter tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-*.xml' 
        failTaskOnFailedTests: true

- stage: onRelease
  condition: |
    or(
      eq(variables['Build.SourceBranch'], 'refs/heads/releases'),
      startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    )
  jobs:
  - job: onReleaseJob
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - script: env | sort
        displayName: 'Environment / Context'

      - task: UsePythonVersion@0
        displayName: 'Use Python 3.7'
        inputs:
          versionSpec: 3.7

      - checkout: self
        persistCredentials: true
        clean: true
        displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

      - script: |
          python -m pip install --upgrade pip nutter
        displayName: 'Install dependencies'

      - script: |
          echo "Checking out the $(Build.SourceBranchName) branch"
          curl -s -n -X POST -o "/tmp/$(Build.SourceBranchName)-out.json" "$DATABRICKS_HOST/api/2.0/projects/fetch-and-checkout" \
            -H "Authorization: Bearer $DATABRICKS_TOKEN" \
            -d "{\"path\": \"/Projects/christopher.chalcraft@databricks.com/Staging\", \"branch\": \"$(Build.SourceBranchName)\"}" && \
            cat "/tmp/$(Build.SourceBranchName)-out.json" && \
            grep -v error_code "/tmp/$(Build.SourceBranchName)-out.json"
        env:
          DATABRICKS_HOST: $(DATABRICKS_HOST)
          DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
        displayName: 'Update Staging project'

# We can do a separate set of the tests for release branches
      - script: |
          nutter run '/Projects/christopher.chalcraft@databricks.com/Staging/' --cluster_id $(CLUSTER_ID) --recursive --junit_report
        env:
          DATABRICKS_HOST: $(DATABRICKS_HOST)
          DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
        displayName: 'Execute Nutter tests on release'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/test-*.xml' 
          failTaskOnFailedTests: true

